---
title: "Feature selection"
author: "Bohdan Valentovic"
date: "November 13, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(lubridate)
```


```{r}
# read the sample file, use the provided header and use coma as the separating character
ktrain <- read.csv('C:\\Users\\Q06409\\Downloads\\Big Data\\CKME-136 Capstone project\\My project\\NYC Taxi Kaggle\\train.csv', header = T, sep = ',')
ktrain  <- read.csv('C:\\Users\\Q06409\\Downloads\\Big Data\\CKME-136 Capstone project\\My project\\NYCT data\\fullTest.csv\\fullTest.csv', header = T, sep = ',')

# Transform pickup day to day of week, day of month, month columns
ktrain$pickup_dow <- as.factor(wday(ktrain$pickup_datetime))
ktrain$pickup_month <- as.factor(month(ktrain$pickup_datetime))
ktrain$pickup_day <- as.factor(day(ktrain$pickup_datetime))
ktrain$pickup_hour <- as.factor(hour(ktrain$pickup_datetime))
ktrain$pickup_minute <- as.factor(minute(ktrain$pickup_datetime))

summary(ktrain)

```
